train_start_date: "2016-02-01"
train_end_date: "2016-05-15"

lgb_params:
    "objective": "tweedie"
    "n_estimators": 2
    "learning_rate": 0.1
    "subsample": 0.8
    "colsample_bytree": 0.8
    "max_depth": 8
    "num_leaves": 50
    "min_child_weight": 300
    "metric": "rmse"
    "verbose": 10

store_list: ["CA_1"]

pred_week_list: [1]
